### ISSUE TITLE
Doesnt work anymore..

### ISSUE THREAD

**Issue by ghost** [TheOddball/oddBES#3]
Especially quick listing, it just highlights the items but when you press the quicklist button it only does the first one.

There is no settings either..

**Comment by TheOddball** [comment]
Yeah, I understand the issues.
Im working towards a fix, Fiskie changed _everything_ with the new update, and its very hard to decode.

**Comment by ghost** [comment]
Oh okay, how dare he change everything ;) Good luck! :)

**Comment by TheOddball** [comment]
Fixed with newest version
